### ISSUE TITLE
pBTC balance is taking more time(more than expected blocks) to reflect the BTC transferred [deposit]

### ISSUE THREAD

**Issue by pbattu123** [peerplays-network/peerplays#24]
Technically speaking pBTC of an account should get updated with transferred BTC after 6 blocks on Bitcoin node and 7 blocks on PPY node. But it's taking more blocks(long time) for confirmations(tested in -regtest mode)

1. Bring up both nodes and start transferring BTC to peerplays address
2. After transferring BTC, generate few blocks on bitcoin node and wait for PPY node to produce 7 blocks(In debug mode you can observe bitcoin transaction in the logs)
3. Check pBTC balance and it updates's correctly.
4. Initiate one more transaction to the same account and generate few more BTC blocks(7 or 8)  and wait for PPY to generate 7 more blocks to reflect the transactions.
5. pBTC should get updated but it is not.
6. Generate one more bitcoin block, still pBTC is not updated.
7. Generate 10 more bitcoin blocks, then pBTC updated. This means on the main net, it's going to take long time.

**Comment by bobinson** [comment]
@pbattu123 : in total how many blocks and confirmations are required for the pBTC balance update as of now ?

**Comment by pbattu123** [comment]
> @pbattu123 : in total how many blocks and confirmations are required for the pBTC balance update as of now ?

More than 12 blocks on bitcoin node

**Comment by bobinson** [comment]
@slzvrg : test

**Comment by pixelplex** [comment]
@bobinson NVM, going to be posting from this account to avoid any issues. @pbattu123 Would it be correct to assume that one-node PeerPlays setup was used, and not a network?

**Comment by pbattu123** [comment]
> @bobinson NVM, going to be posting from this account to avoid any issues. @pbattu123 Would it be correct to assume that one-node PeerPlays setup was used, and not a network?

Yes with one PPY node

**Comment by pixelplex** [comment]
@pbattu123 
Please make sure you follow the guide and take these points into consideration (for deposits):
1) After a Bitcoin deposit transaction is sent to the deposit address, it needs to be added to the block (1 confirmation).
2) Once that is done, an operation + 5 confirmations on PeerPlays needs to occur (6 in total).
3) Once that happens, a transaction is generated sending BTC from deposit address to PW (which requires 6 confirmations on Bitcoin)
4) Once that happens, a proposal on PeerPlays to issue pBTC needs to be created and signed 5 times (i.e. 1+5 blocks).

**Comment by bobinson** [comment]
@pixelplex : Please confirm the below is the expected behavior:

The above six steps are slightly extended by adding respective Blockchains

1. Generate a BTC deposit address for an account already present on Peerplays account (btc_deposit_address)
2. Send BTC to the account created in Step 1 (btc_deposit_address)
3. After a Bitcoin deposit transaction is carried out to sent BTC to the deposit address, it needs to be added to the Bitcoin blockchain block (1 confirmation).
4. Once the transfer operation followed by one confirmation is completed on the Bitcoin Blockchain, an operation + 5 confirmations on PeerPlays needs to occur (6 in total confirmations on the Peerplays blockchain).
5. Once step 4 on Peerplays Blockchain is completed, a transaction is generated to send BTC from deposit address to PW. (This requires 6 confirmations on the Bitcoin blockchain to complete)
6. Subject to completion of step5, a proposal on Peerplays to issue pBTC needs to be created and signed 5 times. (ie, total 5+1 blocks on the Peerplays Blockchain)

**Comment by pbattu123** [comment]
The steps are detailed as above, we need to follow the steps instead of simply generating 6 and 6 blocks to make sure the transaction taking right confirmations.
